name: Build
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2

            - name: Extract Version
              id: version
              run: |
                  VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.source == null) | .version')
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Build
              run: cargo build --release --verbose

            - name: Run tests
              run: cargo test --release --verbose

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ env.VERSION }}
